### ISSUE TITLE
Exception when running IPython 3.0.0-dev Notebook with IScala kernel

### ISSUE THREAD

**Issue by romovpa** [mattpap/IScala#19]
I want to use your awesome kernel with ipython 3.0.0-dev (current master).

I've created kernel-file `iscala/kernel.json`:

``` json
{
 "argv": ["java", "-jar", "/Users/romovpa/workspace/iscala/IScala-0.1/lib/IScala.jar", "--profile", "{connection_file}", "--parent"],
 "display_name": "IScala",
 "language": "scala"
}
```

And, woohoo, it works in console mode:

```
romovpa@95:~$ ipython console --kernel iscala
IPython Console 3.0.0-dev
Welcome to Scala 2.10.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_05)

In [1]: (1 to 5).foreach { i => println(i); Thread.sleep(1000) }
1
2
3
4
5
```

But when I try to start notebook with IScala kernel, it fails with an exception:

```
romovpa@95:~$ ipython notebook
[I 18:01:21.367 NotebookApp] Using existing profile dir: u'/Users/romovpa/.ipython/profile_default'
...
[I 18:01:29.894 NotebookApp] Kernel started: ef9d90e1-b356-4495-b319-66fece8006f6
Exception in thread "main" joptsimple.UnrecognizedOptionException: 'profile-dir' is not a recognized option
    at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:493)
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
    at joptsimple.OptionParser.parse(OptionParser.java:433)
    at org.refptr.iscala.Options.<init>(Options.scala:12)
    at org.refptr.iscala.IScala$delayedInit$body.apply(IScala.scala:15)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at org.refptr.iscala.IScala$.main(IScala.scala:14)
    at org.refptr.iscala.IScala.main(IScala.scala)
```

Is it a big problem? What do we need to fix notebook mode?

**Comment by mathieu1** [comment]
Are you still having this issue? I got an IScala kernel running fine in IPNB3. The only difference between my setup and yours is that I have `"--connection-file"` instead of `"--profile"` (reflecting the latest changes).

Once you get it running, don't forget to add the following image in your kernel folder (`iscala/`) and rename it `logo-64x64.png` to get the Scala logo on any ~~ipython~~ Jupyter notebook using that kernel ;)
![logo-64x64](https://cloud.githubusercontent.com/assets/7703352/5563970/c874fa94-8ea0-11e4-91fc-e335197e7eb8.png)

**Comment by jddavis-100** [comment]
thank you!  That's very helpful.  I'm not using Scala right now, but I will
pass this on to my colleague.  We will be using it in the new year.  Happy
Holidays!

On Sun, Dec 28, 2014 at 8:08 AM, Mathieu notifications@github.com wrote:

> Are you still having this issue? I got an IScala kernel running fine in
> IPNB3. The only difference between my setup and yours is that I have
> "--connection-file" instead of "--profile" (reflecting the latest
> changes).
> 
> Once you get it running, don't forget to add the following image in your
> kernel folder (iscala/) and rename it logo-64x64.png to get the Scala
> logo on any ipython Jupyter notebook using that kernel ;)
> [image: logo-64x64]
> https://cloud.githubusercontent.com/assets/7703352/5563970/c874fa94-8ea0-11e4-91fc-e335197e7eb8.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mattpap/IScala/issues/19#issuecomment-68207984.

## 

Jennifer Dawn Davis, PhD

Linked In Resume & Profile:
http://www.linkedin.com/in/drjenniferdavis

Disclaimer: This message may contain confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system.

**Comment by lJoublanc** [comment]
What is the relationship between Jupyter and this project? Will this ever get merged into the Jupyter codebase and included with that release?

Sorry didn't know where else to put this question ... this seemed like the most appropriate place.

**Comment by lJoublanc** [comment]
I guess what I'm asking is: will the kernel from this project be used as
the default scala kernel in Jupyter? When that happens, will this project
become obsolete?

**Comment by romovpa** [comment]
It works nice. 
I'm using master branches of IScala and ipython.

My updated configuration:

```
$ ls ~/.ipython/kernels/iscala/
kernel.json    logo-64x64.png
$ cat ~/.ipython/kernels/iscala/kernel.json 
{
 "argv": ["java", "-jar", "/Users/romovpa/workspace/iscala/IScala/target/scala-2.11/lib/IScala.jar", "--connection-file", "{connection_file}"],
 "display_name": "IScala",
 "language": "scala"
}
```

@mathieu1, thank you for the logo and syntax highlighting!
