### ISSUE TITLE
Defining Functions without Arguments

### ISSUE THREAD

**Issue by keithohara** [mattpap/IScala#5]
Is the desired behavior of IScala to call a function immediately after it's defined?

```
In [1]: def f = 42
Out[1]: 42
```

compared with the scala REPL:

```
scala> def f = 42
f: Int

scala> f 
res2: Int = 42
```

**Comment by mattpap** [comment]
No, that's clearly a bug. It affects `lazy val`s as well, e.g.:

```
In [1]: def f = { println("X"); 42 }
X
Out[1]: 42

In [2]: def g() = { println("X"); 42 }
X
Out[2]: 42

In [3]: lazy val x = { println("X"); 42 }
X
Out[3]: 42
```

All shouldn't give any output.

**Comment by mattpap** [comment]
Fixed in https://github.com/mattpap/IScala/commit/bcb080efd9ed57c278e4283264d511eff4a01597.
